apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "order"
  description: "This website handles orders across all types."
  links:
    - url: https://api-order-demobackstage1.empcbr.thoughtworks-labs.net/api
      title: order
      icon: dashboard
  annotations:
    circleci.com/project-slug: github/platform-dx/order-4c56331
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug:  platform-dx/order-4c56331
    sonarqube.org/project-key: "order"
    backstage.io/kubernetes-label-selector: "app=order"
    backstage.io/adr-location: docs/adrs/
spec:
  type: service
  lifecycle: experimental
  owner: "order-team"
  providesApis:
    - "order"
    - "price"
  system: "order"
  subcomponentOf: "shipping"
  consumesApis: 
    - "customer"
  dependsOn: 
    - "orders-db"  
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: order
spec:
  owner: order-team
  
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: john
spec:
  memberOf: [order-team]
---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-group
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: order-team
spec:
  type: team
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: orders-db
  description: Stores order details
spec:
  type: database
  owner: order-team
  system: order
  

  
